name: qorgai
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  http: ^1.3.0

  flutter:
    sdk: flutter

  easy_localization: ^3.0.1
  animated_text_kit: ^4.2.2
  google_fonts: ^6.1.0
  bubble: ^1.2.1
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/translations/
    - assets/icons/

